### ISSUE TITLE
大佬，一起研究啊，我专业数学建模

### ISSUE THREAD

**Issue by yangqianzi** [paladin1013/genius-invokation-gym#1]

**Comment by yangqianzi** [comment]
有兴趣可以私聊我微博 id是：6358805731

**Comment by paladin1013** [comment]
好哇可以互相学习哈哈哈，我也只是用过一点openai的gym，想着能不能搞一个七圣召唤的版本

**Comment by yangqianzi** [comment]
> 
主要是我觉得问题的状态深度没超过50，而且是完整信息。。。简单状态机就可以做了

**Comment by leng-yue** [comment]
有群么, 带我一个 hhh

**Comment by paladin1013** [comment]
![image](https://user-images.githubusercontent.com/70081676/206840858-32f4dd57-f89a-4cdd-b1f4-ebca6e829b5b.png)
建了个群（虽然qq不太常用）
