### ISSUE TITLE
[問題] 請問卡牌資料 API 位址是如何獲得的

### ISSUE THREAD

**Issue by KT-Yeh** [paladin1013/genius-invokation-gym#25]
你好

在 fetch-cards-20221205.py 內的 BASE_URL

像現在新版本有北斗與可莉兩張卡牌，沒有在上述連結裡面，需要再找新的連結

能不能請教一下如何獲得新的 API 連結

**Comment by paladin1013** [comment]
我也不是很清楚，之后打算把每个卡牌都直接生成成py文件，这样如果有了新的卡牌，直接编写新的python文件就可以了

**Comment by paladin1013** [comment]
可以参考神里绫华的文件
